# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WordPadDemoAshutos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WordPadDemoAshutos

  pod "RichEditorView"
  pod 'IQKeyboardManagerSwift'


  target 'WordPadDemoAshutosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WordPadDemoAshutosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
